"""Write protection for purchased/original Guitar Pro scores.

A score is protected when it is byte-identical to a file in the originals folder,
or when it embeds audio and was not generated by BassStation. Every code path
that rewrites a .gp archive must call ``is_protected`` first.
"""
import paths
import hashlib
import json
import os
import zipfile
from functools import lru_cache

ORIGINALS_DIR = paths.ORIGINALS
DERIVED_KEY = "bassstationDerived"


@lru_cache(maxsize=1)
def _original_index():
    idx = {}
    if os.path.isdir(ORIGINALS_DIR):
        for root, _, files in os.walk(ORIGINALS_DIR):
            for f in files:
                if f.lower().endswith((".gp", ".gpx", ".gp5", ".gp4")):
                    p = os.path.join(root, f)
                    idx.setdefault(os.path.getsize(p), []).append(p)
    return idx


def _md5(path):
    h = hashlib.md5()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def is_pristine_original(path: str) -> bool:
    try:
        cands = _original_index().get(os.path.getsize(path), [])
        if not cands:
            return False
        me = _md5(path)
        return any(_md5(c) == me for c in cands)
    except OSError:
        return False


def has_embedded_audio(path: str) -> bool:
    try:
        with zipfile.ZipFile(path) as z:
            return any(i.filename.startswith("Content/Assets/") and i.file_size > 100000 for i in z.infolist())
    except Exception:
        return False


AI_TABBER = "BaSSDream"


def is_derived(path: str) -> bool:
    """Written by BaSSDream: meta.json flag, or (after the user re-saved it in Guitar Pro, which rewrites
    meta.json) the AI transcription's Tabber field. Byte-identical purchased originals never count."""
    try:
        with zipfile.ZipFile(path) as z:
            names = z.namelist()
            if "meta.json" in names and json.loads(z.read("meta.json").decode("utf-8", "ignore")).get(DERIVED_KEY):
                return True
            if "Content/score.gpif" in names:
                head = z.read("Content/score.gpif")[:20000].decode("utf-8", "ignore")
                i = head.find("<Tabber>")
                if i >= 0:
                    tab = head[i + 8:head.find("</Tabber>", i)].replace("<![CDATA[", "").replace("]]>", "").strip()
                    return tab == AI_TABBER and not is_pristine_original(path)
    except Exception:
        pass
    return False


def is_protected(path: str) -> bool:
    if not path or not os.path.exists(path) or not path.lower().endswith(".gp"):
        return False
    if is_derived(path):
        return False
    return is_pristine_original(path) or has_embedded_audio(path)


def derived_meta(has_audio: bool) -> bytes:
    return json.dumps({"hasAudio": has_audio, "version": "1.0.0", DERIVED_KEY: True}, indent=4).encode("utf-8")
